In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("tate.csv",low_memory=False)

In [3]:
data.head()

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
0,Female,"Abakanowicz, Magdalena",artist,Burlap and resin,http://www.tate.org.uk/art/images/work/T/T12/T...,Backs,http://www.tate.org.uk/art/artworks/abakanowic...,0.0,0.0,0.0,2009,1970,1976,Presented anonymously 2009,Polska,1930,NaN,0
1,Male,"Abbey, Edwin Austin",artist,Ink on paper,http://www.tate.org.uk/art/images/work/N/N03/N...,Illustration to Judith Shakespeare,http://www.tate.org.uk/art/artworks/abbey-illu...,0.0,419.0,305.0,1924,1880,1883,Presented by a group of admirers through John ...,"Philadelphia, United States",1852,"London, United Kingdom",1911
2,Female,"Abbott, Berenice",artist,"Photograph, gelatin silver print on paper",NaN,Tri-Boro Barber Shop,http://www.tate.org.uk/art/artworks/abbott-tri...,0.0,200.0,250.0,2010,1930,1935,Accepted by HM Government in lieu of inheritan...,"Springfield, United States",1898,"Monson, United States",1991
3,Male,"Abbott, Lemuel Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T01/T...,Portrait of the Engraver Francesco Bartolozzi,http://www.tate.org.uk/art/artworks/abbott-por...,0.0,676.0,756.0,1968,0,0,Presented by Mrs M. Bernard 1968,"Leicestershire, United Kingdom",1760,"London, United Kingdom",1803
4,Male,"Abrahams, Ivor",artist,Fibreglass and polystyrene,http://www.tate.org.uk/art/images/work/T/T03/T...,Lady in Niche,http://www.tate.org.uk/art/artworks/abrahams-l...,762.0,1575.0,2095.0,1982,1970,1973,Purchased 1982,"Wigan, United Kingdom",1935,NaN,0

In [4]:
data.loc[data['data.medium'].str.contains('\s$',regex=True)]  #to find white spaces in the end of the string

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
392,Male,"Broomberg, Adam",artist,Digital print on paper,http://www.tate.org.uk/art/images/work/P/P13/P...,Political 1 sheet 19,http://www.tate.org.uk/art/artworks/broomberg-...,0.0,1900.0,1500.0,2013,2010,2010,Presented anonymously 2012,"Johannesburg, South Africa",1970,NaN,0
571,Male,"City Racing (Matt Hale; Paul Noble, born 1963;...",artist,"Marker pen, photographs and printed papers on ...",NaN,City Racing Family Tree,http://www.tate.org.uk/art/artworks/city-racin...,20.0,6100.0,2442.0,2002,2000,2000,Purchased 2002,NaN,1988,NaN,0
953,Female,"Falkenstein, Claire",artist,Copper and silver on wooden base,NaN,Point as a Set No. 26,http://www.tate.org.uk/art/artworks/falkenstei...,762.0,762.0,762.0,1970,1970,1970,Presented by the artist 1970,"Coos Bay, United States",1909,NaN,1997
1170,Male,"Gordon, Douglas",artist,"Video, projection, colour and sound",NaN,Feature Film,http://www.tate.org.uk/art/artworks/gordon-fea...,0.0,0.0,0.0,2013,1990,1999,Presented by the artist and Artangel 2012. The...,"Glasgow, United Kingdom",1966,NaN,0
2482,Female,"Raven, Lucy",artist,"Video, projection, colour and sound (stereo)",NaN,China Town,http://www.tate.org.uk/art/artworks/raven-chin...,0.0,0.0,0.0,2013,2000,2009,Purchased with funds provided by Bilge Ogut-Cu...,NaN,1977,NaN,0
3151,Female,"Warren, Rebecca",artist,"Perspex, wood, neon gas, glass, plastic, wool,...",http://www.tate.org.uk/art/images/work/T/T12/T...,In The Bois,http://www.tate.org.uk/art/artworks/warren-in-...,322.0,1603.0,580.0,2008,2000,2005,Presented by Tate Patrons 2008,"London, United Kingdom",1965,NaN,0

In [5]:
data['data.medium'].str.strip()     #removed

0                                        Burlap and resin
1                                            Ink on paper
2               Photograph, gelatin silver print on paper
3                                     Oil paint on canvas
4                              Fibreglass and polystyrene
                              ...
3327                                  Oil paint on canvas
3328                                  Oil paint on canvas
3329                                  Lithograph on paper
3330    Photograph, colour, on paper with acrylic pain...
3331                Photograph, black and white, on paper
Name: data.medium, Length: 3332, dtype: object

In [6]:
data.loc[data['data.medium'].str.contains('\s$',regex=True)]   #no change in original data

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
392,Male,"Broomberg, Adam",artist,Digital print on paper,http://www.tate.org.uk/art/images/work/P/P13/P...,Political 1 sheet 19,http://www.tate.org.uk/art/artworks/broomberg-...,0.0,1900.0,1500.0,2013,2010,2010,Presented anonymously 2012,"Johannesburg, South Africa",1970,NaN,0
571,Male,"City Racing (Matt Hale; Paul Noble, born 1963;...",artist,"Marker pen, photographs and printed papers on ...",NaN,City Racing Family Tree,http://www.tate.org.uk/art/artworks/city-racin...,20.0,6100.0,2442.0,2002,2000,2000,Purchased 2002,NaN,1988,NaN,0
953,Female,"Falkenstein, Claire",artist,Copper and silver on wooden base,NaN,Point as a Set No. 26,http://www.tate.org.uk/art/artworks/falkenstei...,762.0,762.0,762.0,1970,1970,1970,Presented by the artist 1970,"Coos Bay, United States",1909,NaN,1997
1170,Male,"Gordon, Douglas",artist,"Video, projection, colour and sound",NaN,Feature Film,http://www.tate.org.uk/art/artworks/gordon-fea...,0.0,0.0,0.0,2013,1990,1999,Presented by the artist and Artangel 2012. The...,"Glasgow, United Kingdom",1966,NaN,0
2482,Female,"Raven, Lucy",artist,"Video, projection, colour and sound (stereo)",NaN,China Town,http://www.tate.org.uk/art/artworks/raven-chin...,0.0,0.0,0.0,2013,2000,2009,Purchased with funds provided by Bilge Ogut-Cu...,NaN,1977,NaN,0
3151,Female,"Warren, Rebecca",artist,"Perspex, wood, neon gas, glass, plastic, wool,...",http://www.tate.org.uk/art/images/work/T/T12/T...,In The Bois,http://www.tate.org.uk/art/artworks/warren-in-...,322.0,1603.0,580.0,2008,2000,2005,Presented by Tate Patrons 2008,"London, United Kingdom",1965,NaN,0

In [7]:
data['data.medium'] = data['data.medium'].str.strip() #original data changed

In [8]:
data.loc[data['data.medium'].str.contains('\s$',regex=True)]

Empty DataFrame
Columns: [artist.gender, artist.name, artist.role, data.medium, data.thumbnail, data.title, data.url, dimensions.depth, dimensions.height, dimensions.width, metadata.acquisition date, metadata.creation decade, metadata.creation year, metadata.credit, artist.birth.location, artist.birth.year, artist.death.location, artist.death.year]
Index: []

In [9]:
data['data.medium'].str.rstrip()     #strips to the right

0                                        Burlap and resin
1                                            Ink on paper
2               Photograph, gelatin silver print on paper
3                                     Oil paint on canvas
4                              Fibreglass and polystyrene
                              ...
3327                                  Oil paint on canvas
3328                                  Oil paint on canvas
3329                                  Lithograph on paper
3330    Photograph, colour, on paper with acrylic pain...
3331                Photograph, black and white, on paper
Name: data.medium, Length: 3332, dtype: object

In [10]:
data['data.medium'].str.lstrip()     #strips to the left

0                                        Burlap and resin
1                                            Ink on paper
2               Photograph, gelatin silver print on paper
3                                     Oil paint on canvas
4                              Fibreglass and polystyrene
                              ...
3327                                  Oil paint on canvas
3328                                  Oil paint on canvas
3329                                  Lithograph on paper
3330    Photograph, colour, on paper with acrylic pain...
3331                Photograph, black and white, on paper
Name: data.medium, Length: 3332, dtype: object

In [11]:
data['data.medium'].transform(lambda x:x.strip())   #using transform function

0                                        Burlap and resin
1                                            Ink on paper
2               Photograph, gelatin silver print on paper
3                                     Oil paint on canvas
4                              Fibreglass and polystyrene
                              ...
3327                                  Oil paint on canvas
3328                                  Oil paint on canvas
3329                                  Lithograph on paper
3330    Photograph, colour, on paper with acrylic pain...
3331                Photograph, black and white, on paper
Name: data.medium, Length: 3332, dtype: object

# Replacing BadData

In [12]:
data = pd.read_csv("tate.csv",low_memory=False)
data

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
0,Female,"Abakanowicz, Magdalena",artist,Burlap and resin,http://www.tate.org.uk/art/images/work/T/T12/T...,Backs,http://www.tate.org.uk/art/artworks/abakanowic...,0.0,0.0,0.0,2009,1970,1976,Presented anonymously 2009,Polska,1930,NaN,0
1,Male,"Abbey, Edwin Austin",artist,Ink on paper,http://www.tate.org.uk/art/images/work/N/N03/N...,Illustration to Judith Shakespeare,http://www.tate.org.uk/art/artworks/abbey-illu...,0.0,419.0,305.0,1924,1880,1883,Presented by a group of admirers through John ...,"Philadelphia, United States",1852,"London, United Kingdom",1911
2,Female,"Abbott, Berenice",artist,"Photograph, gelatin silver print on paper",NaN,Tri-Boro Barber Shop,http://www.tate.org.uk/art/artworks/abbott-tri...,0.0,200.0,250.0,2010,1930,1935,Accepted by HM Government in lieu of inheritan...,"Springfield, United States",1898,"Monson, United States",1991
3,Male,"Abbott, Lemuel Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T01/T...,Portrait of the Engraver Francesco Bartolozzi,http://www.tate.org.uk/art/artworks/abbott-por...,0.0,676.0,756.0,1968,0,0,Presented by Mrs M. Bernard 1968,"Leicestershire, United Kingdom",1760,"London, United Kingdom",1803
4,Male,"Abrahams, Ivor",artist,Fibreglass and polystyrene,http://www.tate.org.uk/art/images/work/T/T03/T...,Lady in Niche,http://www.tate.org.uk/art/artworks/abrahams-l...,762.0,1575.0,2095.0,1982,1970,1973,Purchased 1982,"Wigan, United Kingdom",1935,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3327,Male,"Zuloaga, Ignacio",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/N/N01/N...,View of the Escorial,http://www.tate.org.uk/art/artworks/zuloaga-vi...,0.0,406.0,292.0,1923,1900,1905,Presented by T.W. Bacon through the Art Fund 1923,Espaa,1870,Espaa,1945
3328,Male,"Zyw, Aleksander",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T00/T...,Light,http://www.tate.org.uk/art/artworks/zyw-light-...,28.0,662.0,934.0,1962,1950,1957,Presented by Lady Alice Egerton through the Fr...,Polska,1905,NaN,1995
3329,Male,"di Suvero, Mark",artist,Lithograph on paper,NaN,Tetra,http://www.tate.org.uk/art/artworks/di-suvero-...,0.0,843.0,1152.0,2004,1970,1976,Presented by Tyler Graphics Ltd in honour of P...,"Shanghai, Zhonghua",1933,NaN,0
3330,Male,"van Elk, Ger",artist,"Photograph, colour, on paper with acrylic pain...",NaN,Lunch II,http://www.tate.org.uk/art/artworks/van-elk-lu...,0.0,1000.0,800.0,1980,1970,1976,Purchased 1980,"Amsterdam, Nederland",1941,NaN,0
3331,Male,"tyrsk, Jindrich",artist,"Photograph, black and white, on paper",http://www.tate.org.uk/art/images/work/P/P79/P...,Untitled,http://www.tate.org.uk/art/artworks/styrsky-un...,0.0,0.0,0.0,2007,1930,1934,Purchased 2007,NaN,1899,"Praha, Cesk Republika",1942

In [13]:
pd.isna(data.loc[:,'artist.death.location'])   #checking for na values

0        True
1       False
2       False
3       False
4        True
        ...
3327    False
3328     True
3329     True
3330     True
3331    False
Name: artist.death.location, Length: 3332, dtype: bool

In [14]:
from numpy import nan

In [15]:
data.replace({'artist.death.location':{'Not known':nan}},inplace=True)     #replacing with na inplace of any value

In [16]:
data.head()

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
0,Female,"Abakanowicz, Magdalena",artist,Burlap and resin,http://www.tate.org.uk/art/images/work/T/T12/T...,Backs,http://www.tate.org.uk/art/artworks/abakanowic...,0.0,0.0,0.0,2009,1970,1976,Presented anonymously 2009,Polska,1930,NaN,0
1,Male,"Abbey, Edwin Austin",artist,Ink on paper,http://www.tate.org.uk/art/images/work/N/N03/N...,Illustration to Judith Shakespeare,http://www.tate.org.uk/art/artworks/abbey-illu...,0.0,419.0,305.0,1924,1880,1883,Presented by a group of admirers through John ...,"Philadelphia, United States",1852,"London, United Kingdom",1911
2,Female,"Abbott, Berenice",artist,"Photograph, gelatin silver print on paper",NaN,Tri-Boro Barber Shop,http://www.tate.org.uk/art/artworks/abbott-tri...,0.0,200.0,250.0,2010,1930,1935,Accepted by HM Government in lieu of inheritan...,"Springfield, United States",1898,"Monson, United States",1991
3,Male,"Abbott, Lemuel Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T01/T...,Portrait of the Engraver Francesco Bartolozzi,http://www.tate.org.uk/art/artworks/abbott-por...,0.0,676.0,756.0,1968,0,0,Presented by Mrs M. Bernard 1968,"Leicestershire, United Kingdom",1760,"London, United Kingdom",1803
4,Male,"Abrahams, Ivor",artist,Fibreglass and polystyrene,http://www.tate.org.uk/art/images/work/T/T03/T...,Lady in Niche,http://www.tate.org.uk/art/artworks/abrahams-l...,762.0,1575.0,2095.0,1982,1970,1973,Purchased 1982,"Wigan, United Kingdom",1935,NaN,0

In [17]:
data = pd.read_csv("tate.csv",low_memory=False)
data

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
0,Female,"Abakanowicz, Magdalena",artist,Burlap and resin,http://www.tate.org.uk/art/images/work/T/T12/T...,Backs,http://www.tate.org.uk/art/artworks/abakanowic...,0.0,0.0,0.0,2009,1970,1976,Presented anonymously 2009,Polska,1930,NaN,0
1,Male,"Abbey, Edwin Austin",artist,Ink on paper,http://www.tate.org.uk/art/images/work/N/N03/N...,Illustration to Judith Shakespeare,http://www.tate.org.uk/art/artworks/abbey-illu...,0.0,419.0,305.0,1924,1880,1883,Presented by a group of admirers through John ...,"Philadelphia, United States",1852,"London, United Kingdom",1911
2,Female,"Abbott, Berenice",artist,"Photograph, gelatin silver print on paper",NaN,Tri-Boro Barber Shop,http://www.tate.org.uk/art/artworks/abbott-tri...,0.0,200.0,250.0,2010,1930,1935,Accepted by HM Government in lieu of inheritan...,"Springfield, United States",1898,"Monson, United States",1991
3,Male,"Abbott, Lemuel Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T01/T...,Portrait of the Engraver Francesco Bartolozzi,http://www.tate.org.uk/art/artworks/abbott-por...,0.0,676.0,756.0,1968,0,0,Presented by Mrs M. Bernard 1968,"Leicestershire, United Kingdom",1760,"London, United Kingdom",1803
4,Male,"Abrahams, Ivor",artist,Fibreglass and polystyrene,http://www.tate.org.uk/art/images/work/T/T03/T...,Lady in Niche,http://www.tate.org.uk/art/artworks/abrahams-l...,762.0,1575.0,2095.0,1982,1970,1973,Purchased 1982,"Wigan, United Kingdom",1935,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3327,Male,"Zuloaga, Ignacio",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/N/N01/N...,View of the Escorial,http://www.tate.org.uk/art/artworks/zuloaga-vi...,0.0,406.0,292.0,1923,1900,1905,Presented by T.W. Bacon through the Art Fund 1923,Espaa,1870,Espaa,1945
3328,Male,"Zyw, Aleksander",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T00/T...,Light,http://www.tate.org.uk/art/artworks/zyw-light-...,28.0,662.0,934.0,1962,1950,1957,Presented by Lady Alice Egerton through the Fr...,Polska,1905,NaN,1995
3329,Male,"di Suvero, Mark",artist,Lithograph on paper,NaN,Tetra,http://www.tate.org.uk/art/artworks/di-suvero-...,0.0,843.0,1152.0,2004,1970,1976,Presented by Tyler Graphics Ltd in honour of P...,"Shanghai, Zhonghua",1933,NaN,0
3330,Male,"van Elk, Ger",artist,"Photograph, colour, on paper with acrylic pain...",NaN,Lunch II,http://www.tate.org.uk/art/artworks/van-elk-lu...,0.0,1000.0,800.0,1980,1970,1976,Purchased 1980,"Amsterdam, Nederland",1941,NaN,0
3331,Male,"tyrsk, Jindrich",artist,"Photograph, black and white, on paper",http://www.tate.org.uk/art/images/work/P/P79/P...,Untitled,http://www.tate.org.uk/art/artworks/styrsky-un...,0.0,0.0,0.0,2007,1930,1934,Purchased 2007,NaN,1899,"Praha, Cesk Republika",1942

In [18]:
data.loc[data['artist.death.location'] == 'not known',['artist.death.location']] = nan   #another way of replacing

In [19]:
data.head()

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
0,Female,"Abakanowicz, Magdalena",artist,Burlap and resin,http://www.tate.org.uk/art/images/work/T/T12/T...,Backs,http://www.tate.org.uk/art/artworks/abakanowic...,0.0,0.0,0.0,2009,1970,1976,Presented anonymously 2009,Polska,1930,NaN,0
1,Male,"Abbey, Edwin Austin",artist,Ink on paper,http://www.tate.org.uk/art/images/work/N/N03/N...,Illustration to Judith Shakespeare,http://www.tate.org.uk/art/artworks/abbey-illu...,0.0,419.0,305.0,1924,1880,1883,Presented by a group of admirers through John ...,"Philadelphia, United States",1852,"London, United Kingdom",1911
2,Female,"Abbott, Berenice",artist,"Photograph, gelatin silver print on paper",NaN,Tri-Boro Barber Shop,http://www.tate.org.uk/art/artworks/abbott-tri...,0.0,200.0,250.0,2010,1930,1935,Accepted by HM Government in lieu of inheritan...,"Springfield, United States",1898,"Monson, United States",1991
3,Male,"Abbott, Lemuel Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T01/T...,Portrait of the Engraver Francesco Bartolozzi,http://www.tate.org.uk/art/artworks/abbott-por...,0.0,676.0,756.0,1968,0,0,Presented by Mrs M. Bernard 1968,"Leicestershire, United Kingdom",1760,"London, United Kingdom",1803
4,Male,"Abrahams, Ivor",artist,Fibreglass and polystyrene,http://www.tate.org.uk/art/images/work/T/T03/T...,Lady in Niche,http://www.tate.org.uk/art/artworks/abrahams-l...,762.0,1575.0,2095.0,1982,1970,1973,Purchased 1982,"Wigan, United Kingdom",1935,NaN,0

In [20]:
data.loc[data['metadata.creation year'].notnull() & data['metadata.creation year'].astype(str).str.contains('[^0-9]')]    
# If found any bad years(like string values), they can be found here

Empty DataFrame
Columns: [artist.gender, artist.name, artist.role, data.medium, data.thumbnail, data.title, data.url, dimensions.depth, dimensions.height, dimensions.width, metadata.acquisition date, metadata.creation decade, metadata.creation year, metadata.credit, artist.birth.location, artist.birth.year, artist.death.location, artist.death.year]
Index: []

In [21]:
data.loc[data['metadata.creation year'].notnull() & data['metadata.creation year'].astype(str).str.contains('[^0-9]'),['metadata.creation year']] = nan
#converted bad values to nan

# Filling Missing Data

In [22]:
data = pd.read_csv("tate.csv",low_memory=False)

In [23]:
data.head()

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
0,Female,"Abakanowicz, Magdalena",artist,Burlap and resin,http://www.tate.org.uk/art/images/work/T/T12/T...,Backs,http://www.tate.org.uk/art/artworks/abakanowic...,0.0,0.0,0.0,2009,1970,1976,Presented anonymously 2009,Polska,1930,NaN,0
1,Male,"Abbey, Edwin Austin",artist,Ink on paper,http://www.tate.org.uk/art/images/work/N/N03/N...,Illustration to Judith Shakespeare,http://www.tate.org.uk/art/artworks/abbey-illu...,0.0,419.0,305.0,1924,1880,1883,Presented by a group of admirers through John ...,"Philadelphia, United States",1852,"London, United Kingdom",1911
2,Female,"Abbott, Berenice",artist,"Photograph, gelatin silver print on paper",NaN,Tri-Boro Barber Shop,http://www.tate.org.uk/art/artworks/abbott-tri...,0.0,200.0,250.0,2010,1930,1935,Accepted by HM Government in lieu of inheritan...,"Springfield, United States",1898,"Monson, United States",1991
3,Male,"Abbott, Lemuel Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T01/T...,Portrait of the Engraver Francesco Bartolozzi,http://www.tate.org.uk/art/artworks/abbott-por...,0.0,676.0,756.0,1968,0,0,Presented by Mrs M. Bernard 1968,"Leicestershire, United Kingdom",1760,"London, United Kingdom",1803
4,Male,"Abrahams, Ivor",artist,Fibreglass and polystyrene,http://www.tate.org.uk/art/images/work/T/T03/T...,Lady in Niche,http://www.tate.org.uk/art/artworks/abrahams-l...,762.0,1575.0,2095.0,1982,1970,1973,Purchased 1982,"Wigan, United Kingdom",1935,NaN,0

In [24]:
data.fillna(0)   #All 'na' values in the dataframe is filled with '0'

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
0,Female,"Abakanowicz, Magdalena",artist,Burlap and resin,http://www.tate.org.uk/art/images/work/T/T12/T...,Backs,http://www.tate.org.uk/art/artworks/abakanowic...,0.0,0.0,0.0,2009,1970,1976,Presented anonymously 2009,Polska,1930,0,0
1,Male,"Abbey, Edwin Austin",artist,Ink on paper,http://www.tate.org.uk/art/images/work/N/N03/N...,Illustration to Judith Shakespeare,http://www.tate.org.uk/art/artworks/abbey-illu...,0.0,419.0,305.0,1924,1880,1883,Presented by a group of admirers through John ...,"Philadelphia, United States",1852,"London, United Kingdom",1911
2,Female,"Abbott, Berenice",artist,"Photograph, gelatin silver print on paper",0,Tri-Boro Barber Shop,http://www.tate.org.uk/art/artworks/abbott-tri...,0.0,200.0,250.0,2010,1930,1935,Accepted by HM Government in lieu of inheritan...,"Springfield, United States",1898,"Monson, United States",1991
3,Male,"Abbott, Lemuel Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T01/T...,Portrait of the Engraver Francesco Bartolozzi,http://www.tate.org.uk/art/artworks/abbott-por...,0.0,676.0,756.0,1968,0,0,Presented by Mrs M. Bernard 1968,"Leicestershire, United Kingdom",1760,"London, United Kingdom",1803
4,Male,"Abrahams, Ivor",artist,Fibreglass and polystyrene,http://www.tate.org.uk/art/images/work/T/T03/T...,Lady in Niche,http://www.tate.org.uk/art/artworks/abrahams-l...,762.0,1575.0,2095.0,1982,1970,1973,Purchased 1982,"Wigan, United Kingdom",1935,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3327,Male,"Zuloaga, Ignacio",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/N/N01/N...,View of the Escorial,http://www.tate.org.uk/art/artworks/zuloaga-vi...,0.0,406.0,292.0,1923,1900,1905,Presented by T.W. Bacon through the Art Fund 1923,Espaa,1870,Espaa,1945
3328,Male,"Zyw, Aleksander",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T00/T...,Light,http://www.tate.org.uk/art/artworks/zyw-light-...,28.0,662.0,934.0,1962,1950,1957,Presented by Lady Alice Egerton through the Fr...,Polska,1905,0,1995
3329,Male,"di Suvero, Mark",artist,Lithograph on paper,0,Tetra,http://www.tate.org.uk/art/artworks/di-suvero-...,0.0,843.0,1152.0,2004,1970,1976,Presented by Tyler Graphics Ltd in honour of P...,"Shanghai, Zhonghua",1933,0,0
3330,Male,"van Elk, Ger",artist,"Photograph, colour, on paper with acrylic pain...",0,Lunch II,http://www.tate.org.uk/art/artworks/van-elk-lu...,0.0,1000.0,800.0,1980,1970,1976,Purchased 1980,"Amsterdam, Nederland",1941,0,0
3331,Male,"tyrsk, Jindrich",artist,"Photograph, black and white, on paper",http://www.tate.org.uk/art/images/work/P/P79/P...,Untitled,http://www.tate.org.uk/art/artworks/styrsky-un...,0.0,0.0,0.0,2007,1930,1934,Purchased 2007,0,1899,"Praha, Cesk Republika",1942

In [25]:
data.fillna(value={'artist.death.location':0})   #only specific column

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
0,Female,"Abakanowicz, Magdalena",artist,Burlap and resin,http://www.tate.org.uk/art/images/work/T/T12/T...,Backs,http://www.tate.org.uk/art/artworks/abakanowic...,0.0,0.0,0.0,2009,1970,1976,Presented anonymously 2009,Polska,1930,0,0
1,Male,"Abbey, Edwin Austin",artist,Ink on paper,http://www.tate.org.uk/art/images/work/N/N03/N...,Illustration to Judith Shakespeare,http://www.tate.org.uk/art/artworks/abbey-illu...,0.0,419.0,305.0,1924,1880,1883,Presented by a group of admirers through John ...,"Philadelphia, United States",1852,"London, United Kingdom",1911
2,Female,"Abbott, Berenice",artist,"Photograph, gelatin silver print on paper",NaN,Tri-Boro Barber Shop,http://www.tate.org.uk/art/artworks/abbott-tri...,0.0,200.0,250.0,2010,1930,1935,Accepted by HM Government in lieu of inheritan...,"Springfield, United States",1898,"Monson, United States",1991
3,Male,"Abbott, Lemuel Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T01/T...,Portrait of the Engraver Francesco Bartolozzi,http://www.tate.org.uk/art/artworks/abbott-por...,0.0,676.0,756.0,1968,0,0,Presented by Mrs M. Bernard 1968,"Leicestershire, United Kingdom",1760,"London, United Kingdom",1803
4,Male,"Abrahams, Ivor",artist,Fibreglass and polystyrene,http://www.tate.org.uk/art/images/work/T/T03/T...,Lady in Niche,http://www.tate.org.uk/art/artworks/abrahams-l...,762.0,1575.0,2095.0,1982,1970,1973,Purchased 1982,"Wigan, United Kingdom",1935,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3327,Male,"Zuloaga, Ignacio",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/N/N01/N...,View of the Escorial,http://www.tate.org.uk/art/artworks/zuloaga-vi...,0.0,406.0,292.0,1923,1900,1905,Presented by T.W. Bacon through the Art Fund 1923,Espaa,1870,Espaa,1945
3328,Male,"Zyw, Aleksander",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T00/T...,Light,http://www.tate.org.uk/art/artworks/zyw-light-...,28.0,662.0,934.0,1962,1950,1957,Presented by Lady Alice Egerton through the Fr...,Polska,1905,0,1995
3329,Male,"di Suvero, Mark",artist,Lithograph on paper,NaN,Tetra,http://www.tate.org.uk/art/artworks/di-suvero-...,0.0,843.0,1152.0,2004,1970,1976,Presented by Tyler Graphics Ltd in honour of P...,"Shanghai, Zhonghua",1933,0,0
3330,Male,"van Elk, Ger",artist,"Photograph, colour, on paper with acrylic pain...",NaN,Lunch II,http://www.tate.org.uk/art/artworks/van-elk-lu...,0.0,1000.0,800.0,1980,1970,1976,Purchased 1980,"Amsterdam, Nederland",1941,0,0
3331,Male,"tyrsk, Jindrich",artist,"Photograph, black and white, on paper",http://www.tate.org.uk/art/images/work/P/P79/P...,Untitled,http://www.tate.org.uk/art/artworks/styrsky-un...,0.0,0.0,0.0,2007,1930,1934,Purchased 2007,NaN,1899,"Praha, Cesk Republika",1942

In [26]:
data.fillna(value={'artist.death.location':'Na'},inplace=True)  #'Na' is filled

In [27]:
data

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
0,Female,"Abakanowicz, Magdalena",artist,Burlap and resin,http://www.tate.org.uk/art/images/work/T/T12/T...,Backs,http://www.tate.org.uk/art/artworks/abakanowic...,0.0,0.0,0.0,2009,1970,1976,Presented anonymously 2009,Polska,1930,Na,0
1,Male,"Abbey, Edwin Austin",artist,Ink on paper,http://www.tate.org.uk/art/images/work/N/N03/N...,Illustration to Judith Shakespeare,http://www.tate.org.uk/art/artworks/abbey-illu...,0.0,419.0,305.0,1924,1880,1883,Presented by a group of admirers through John ...,"Philadelphia, United States",1852,"London, United Kingdom",1911
2,Female,"Abbott, Berenice",artist,"Photograph, gelatin silver print on paper",NaN,Tri-Boro Barber Shop,http://www.tate.org.uk/art/artworks/abbott-tri...,0.0,200.0,250.0,2010,1930,1935,Accepted by HM Government in lieu of inheritan...,"Springfield, United States",1898,"Monson, United States",1991
3,Male,"Abbott, Lemuel Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T01/T...,Portrait of the Engraver Francesco Bartolozzi,http://www.tate.org.uk/art/artworks/abbott-por...,0.0,676.0,756.0,1968,0,0,Presented by Mrs M. Bernard 1968,"Leicestershire, United Kingdom",1760,"London, United Kingdom",1803
4,Male,"Abrahams, Ivor",artist,Fibreglass and polystyrene,http://www.tate.org.uk/art/images/work/T/T03/T...,Lady in Niche,http://www.tate.org.uk/art/artworks/abrahams-l...,762.0,1575.0,2095.0,1982,1970,1973,Purchased 1982,"Wigan, United Kingdom",1935,Na,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3327,Male,"Zuloaga, Ignacio",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/N/N01/N...,View of the Escorial,http://www.tate.org.uk/art/artworks/zuloaga-vi...,0.0,406.0,292.0,1923,1900,1905,Presented by T.W. Bacon through the Art Fund 1923,Espaa,1870,Espaa,1945
3328,Male,"Zyw, Aleksander",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T00/T...,Light,http://www.tate.org.uk/art/artworks/zyw-light-...,28.0,662.0,934.0,1962,1950,1957,Presented by Lady Alice Egerton through the Fr...,Polska,1905,Na,1995
3329,Male,"di Suvero, Mark",artist,Lithograph on paper,NaN,Tetra,http://www.tate.org.uk/art/artworks/di-suvero-...,0.0,843.0,1152.0,2004,1970,1976,Presented by Tyler Graphics Ltd in honour of P...,"Shanghai, Zhonghua",1933,Na,0
3330,Male,"van Elk, Ger",artist,"Photograph, colour, on paper with acrylic pain...",NaN,Lunch II,http://www.tate.org.uk/art/artworks/van-elk-lu...,0.0,1000.0,800.0,1980,1970,1976,Purchased 1980,"Amsterdam, Nederland",1941,Na,0
3331,Male,"tyrsk, Jindrich",artist,"Photograph, black and white, on paper",http://www.tate.org.uk/art/images/work/P/P79/P...,Untitled,http://www.tate.org.uk/art/artworks/styrsky-un...,0.0,0.0,0.0,2007,1930,1934,Purchased 2007,NaN,1899,"Praha, Cesk Republika",1942

# Dropping rows of data

In [28]:
data = pd.read_csv('tate.csv',low_memory=False)

In [29]:
data.head()

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
0,Female,"Abakanowicz, Magdalena",artist,Burlap and resin,http://www.tate.org.uk/art/images/work/T/T12/T...,Backs,http://www.tate.org.uk/art/artworks/abakanowic...,0.0,0.0,0.0,2009,1970,1976,Presented anonymously 2009,Polska,1930,NaN,0
1,Male,"Abbey, Edwin Austin",artist,Ink on paper,http://www.tate.org.uk/art/images/work/N/N03/N...,Illustration to Judith Shakespeare,http://www.tate.org.uk/art/artworks/abbey-illu...,0.0,419.0,305.0,1924,1880,1883,Presented by a group of admirers through John ...,"Philadelphia, United States",1852,"London, United Kingdom",1911
2,Female,"Abbott, Berenice",artist,"Photograph, gelatin silver print on paper",NaN,Tri-Boro Barber Shop,http://www.tate.org.uk/art/artworks/abbott-tri...,0.0,200.0,250.0,2010,1930,1935,Accepted by HM Government in lieu of inheritan...,"Springfield, United States",1898,"Monson, United States",1991
3,Male,"Abbott, Lemuel Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T01/T...,Portrait of the Engraver Francesco Bartolozzi,http://www.tate.org.uk/art/artworks/abbott-por...,0.0,676.0,756.0,1968,0,0,Presented by Mrs M. Bernard 1968,"Leicestershire, United Kingdom",1760,"London, United Kingdom",1803
4,Male,"Abrahams, Ivor",artist,Fibreglass and polystyrene,http://www.tate.org.uk/art/images/work/T/T03/T...,Lady in Niche,http://www.tate.org.uk/art/artworks/abrahams-l...,762.0,1575.0,2095.0,1982,1970,1973,Purchased 1982,"Wigan, United Kingdom",1935,NaN,0

In [30]:
data[54:56]

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
54,Male,"Als, Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T13/T...,Untitled,http://www.tate.org.uk/art/artworks/alys-untit...,20.0,208.0,159.0,2011,2000,2000,Presented by the artist 2010,"Antwerpen, Belgi",1959,NaN,0
55,Male,"Amiconi, Giacomo",artist,"Ink, watercolour and gouache on paper",http://www.tate.org.uk/art/images/work/T/T08/T...,Portrait of a Man,http://www.tate.org.uk/art/artworks/amiconi-po...,0.0,287.0,203.0,1997,0,0,Purchased as part of the Opp Collection with a...,"Napoli, Italia",1682,"Madrid, Espaa",1752

In [31]:
data.shape

(3332, 18)

In [32]:
data.dropna().shape    #drops entire row with 'na' value

(1076, 18)

In [33]:
data.dropna(how="all")   #drops the rows which are all filled with 'na' values

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
0,Female,"Abakanowicz, Magdalena",artist,Burlap and resin,http://www.tate.org.uk/art/images/work/T/T12/T...,Backs,http://www.tate.org.uk/art/artworks/abakanowic...,0.0,0.0,0.0,2009,1970,1976,Presented anonymously 2009,Polska,1930,NaN,0
1,Male,"Abbey, Edwin Austin",artist,Ink on paper,http://www.tate.org.uk/art/images/work/N/N03/N...,Illustration to Judith Shakespeare,http://www.tate.org.uk/art/artworks/abbey-illu...,0.0,419.0,305.0,1924,1880,1883,Presented by a group of admirers through John ...,"Philadelphia, United States",1852,"London, United Kingdom",1911
2,Female,"Abbott, Berenice",artist,"Photograph, gelatin silver print on paper",NaN,Tri-Boro Barber Shop,http://www.tate.org.uk/art/artworks/abbott-tri...,0.0,200.0,250.0,2010,1930,1935,Accepted by HM Government in lieu of inheritan...,"Springfield, United States",1898,"Monson, United States",1991
3,Male,"Abbott, Lemuel Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T01/T...,Portrait of the Engraver Francesco Bartolozzi,http://www.tate.org.uk/art/artworks/abbott-por...,0.0,676.0,756.0,1968,0,0,Presented by Mrs M. Bernard 1968,"Leicestershire, United Kingdom",1760,"London, United Kingdom",1803
4,Male,"Abrahams, Ivor",artist,Fibreglass and polystyrene,http://www.tate.org.uk/art/images/work/T/T03/T...,Lady in Niche,http://www.tate.org.uk/art/artworks/abrahams-l...,762.0,1575.0,2095.0,1982,1970,1973,Purchased 1982,"Wigan, United Kingdom",1935,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3327,Male,"Zuloaga, Ignacio",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/N/N01/N...,View of the Escorial,http://www.tate.org.uk/art/artworks/zuloaga-vi...,0.0,406.0,292.0,1923,1900,1905,Presented by T.W. Bacon through the Art Fund 1923,Espaa,1870,Espaa,1945
3328,Male,"Zyw, Aleksander",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T00/T...,Light,http://www.tate.org.uk/art/artworks/zyw-light-...,28.0,662.0,934.0,1962,1950,1957,Presented by Lady Alice Egerton through the Fr...,Polska,1905,NaN,1995
3329,Male,"di Suvero, Mark",artist,Lithograph on paper,NaN,Tetra,http://www.tate.org.uk/art/artworks/di-suvero-...,0.0,843.0,1152.0,2004,1970,1976,Presented by Tyler Graphics Ltd in honour of P...,"Shanghai, Zhonghua",1933,NaN,0
3330,Male,"van Elk, Ger",artist,"Photograph, colour, on paper with acrylic pain...",NaN,Lunch II,http://www.tate.org.uk/art/artworks/van-elk-lu...,0.0,1000.0,800.0,1980,1970,1976,Purchased 1980,"Amsterdam, Nederland",1941,NaN,0
3331,Male,"tyrsk, Jindrich",artist,"Photograph, black and white, on paper",http://www.tate.org.uk/art/images/work/P/P79/P...,Untitled,http://www.tate.org.uk/art/artworks/styrsky-un...,0.0,0.0,0.0,2007,1930,1934,Purchased 2007,NaN,1899,"Praha, Cesk Republika",1942

In [34]:
data.dropna(how="all").shape   # no row contains all values as 'na'

(3332, 18)

In [35]:
data.dropna(thresh=15).shape        #'thresh'->how many values in a row

(3313, 18)

In [36]:
data.dropna(subset=['metadata.acquisition date','metadata.creation decade']).shape    #dropping specific rows

(3332, 18)

In [37]:
data.dropna(subset=['metadata.acquisition date','metadata.creation decade'],how='all').shape

(3332, 18)

In [38]:
data.shape

(3332, 18)

In [39]:
data.dropna(thresh=15,inplace=True)

In [40]:
data.shape

(3313, 18)

# Identify and Drop Duplicates

In [41]:
data = pd.read_csv("tate.csv")

In [42]:
data.head()

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
0,Female,"Abakanowicz, Magdalena",artist,Burlap and resin,http://www.tate.org.uk/art/images/work/T/T12/T...,Backs,http://www.tate.org.uk/art/artworks/abakanowic...,0.0,0.0,0.0,2009,1970,1976,Presented anonymously 2009,Polska,1930,NaN,0
1,Male,"Abbey, Edwin Austin",artist,Ink on paper,http://www.tate.org.uk/art/images/work/N/N03/N...,Illustration to Judith Shakespeare,http://www.tate.org.uk/art/artworks/abbey-illu...,0.0,419.0,305.0,1924,1880,1883,Presented by a group of admirers through John ...,"Philadelphia, United States",1852,"London, United Kingdom",1911
2,Female,"Abbott, Berenice",artist,"Photograph, gelatin silver print on paper",NaN,Tri-Boro Barber Shop,http://www.tate.org.uk/art/artworks/abbott-tri...,0.0,200.0,250.0,2010,1930,1935,Accepted by HM Government in lieu of inheritan...,"Springfield, United States",1898,"Monson, United States",1991
3,Male,"Abbott, Lemuel Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T01/T...,Portrait of the Engraver Francesco Bartolozzi,http://www.tate.org.uk/art/artworks/abbott-por...,0.0,676.0,756.0,1968,0,0,Presented by Mrs M. Bernard 1968,"Leicestershire, United Kingdom",1760,"London, United Kingdom",1803
4,Male,"Abrahams, Ivor",artist,Fibreglass and polystyrene,http://www.tate.org.uk/art/images/work/T/T03/T...,Lady in Niche,http://www.tate.org.uk/art/artworks/abrahams-l...,762.0,1575.0,2095.0,1982,1970,1973,Purchased 1982,"Wigan, United Kingdom",1935,NaN,0

In [44]:
data.drop_duplicates()    #Drops the rows if two/more rows are same with all values

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
0,Female,"Abakanowicz, Magdalena",artist,Burlap and resin,http://www.tate.org.uk/art/images/work/T/T12/T...,Backs,http://www.tate.org.uk/art/artworks/abakanowic...,0.0,0.0,0.0,2009,1970,1976,Presented anonymously 2009,Polska,1930,NaN,0
1,Male,"Abbey, Edwin Austin",artist,Ink on paper,http://www.tate.org.uk/art/images/work/N/N03/N...,Illustration to Judith Shakespeare,http://www.tate.org.uk/art/artworks/abbey-illu...,0.0,419.0,305.0,1924,1880,1883,Presented by a group of admirers through John ...,"Philadelphia, United States",1852,"London, United Kingdom",1911
2,Female,"Abbott, Berenice",artist,"Photograph, gelatin silver print on paper",NaN,Tri-Boro Barber Shop,http://www.tate.org.uk/art/artworks/abbott-tri...,0.0,200.0,250.0,2010,1930,1935,Accepted by HM Government in lieu of inheritan...,"Springfield, United States",1898,"Monson, United States",1991
3,Male,"Abbott, Lemuel Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T01/T...,Portrait of the Engraver Francesco Bartolozzi,http://www.tate.org.uk/art/artworks/abbott-por...,0.0,676.0,756.0,1968,0,0,Presented by Mrs M. Bernard 1968,"Leicestershire, United Kingdom",1760,"London, United Kingdom",1803
4,Male,"Abrahams, Ivor",artist,Fibreglass and polystyrene,http://www.tate.org.uk/art/images/work/T/T03/T...,Lady in Niche,http://www.tate.org.uk/art/artworks/abrahams-l...,762.0,1575.0,2095.0,1982,1970,1973,Purchased 1982,"Wigan, United Kingdom",1935,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3327,Male,"Zuloaga, Ignacio",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/N/N01/N...,View of the Escorial,http://www.tate.org.uk/art/artworks/zuloaga-vi...,0.0,406.0,292.0,1923,1900,1905,Presented by T.W. Bacon through the Art Fund 1923,Espaa,1870,Espaa,1945
3328,Male,"Zyw, Aleksander",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T00/T...,Light,http://www.tate.org.uk/art/artworks/zyw-light-...,28.0,662.0,934.0,1962,1950,1957,Presented by Lady Alice Egerton through the Fr...,Polska,1905,NaN,1995
3329,Male,"di Suvero, Mark",artist,Lithograph on paper,NaN,Tetra,http://www.tate.org.uk/art/artworks/di-suvero-...,0.0,843.0,1152.0,2004,1970,1976,Presented by Tyler Graphics Ltd in honour of P...,"Shanghai, Zhonghua",1933,NaN,0
3330,Male,"van Elk, Ger",artist,"Photograph, colour, on paper with acrylic pain...",NaN,Lunch II,http://www.tate.org.uk/art/artworks/van-elk-lu...,0.0,1000.0,800.0,1980,1970,1976,Purchased 1980,"Amsterdam, Nederland",1941,NaN,0
3331,Male,"tyrsk, Jindrich",artist,"Photograph, black and white, on paper",http://www.tate.org.uk/art/images/work/P/P79/P...,Untitled,http://www.tate.org.uk/art/artworks/styrsky-un...,0.0,0.0,0.0,2007,1930,1934,Purchased 2007,NaN,1899,"Praha, Cesk Republika",1942

In [45]:
data.drop_duplicates(subset = ['data.title'])  #removed the rows with same name in the title column

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
0,Female,"Abakanowicz, Magdalena",artist,Burlap and resin,http://www.tate.org.uk/art/images/work/T/T12/T...,Backs,http://www.tate.org.uk/art/artworks/abakanowic...,0.0,0.0,0.0,2009,1970,1976,Presented anonymously 2009,Polska,1930,NaN,0
1,Male,"Abbey, Edwin Austin",artist,Ink on paper,http://www.tate.org.uk/art/images/work/N/N03/N...,Illustration to Judith Shakespeare,http://www.tate.org.uk/art/artworks/abbey-illu...,0.0,419.0,305.0,1924,1880,1883,Presented by a group of admirers through John ...,"Philadelphia, United States",1852,"London, United Kingdom",1911
2,Female,"Abbott, Berenice",artist,"Photograph, gelatin silver print on paper",NaN,Tri-Boro Barber Shop,http://www.tate.org.uk/art/artworks/abbott-tri...,0.0,200.0,250.0,2010,1930,1935,Accepted by HM Government in lieu of inheritan...,"Springfield, United States",1898,"Monson, United States",1991
3,Male,"Abbott, Lemuel Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T01/T...,Portrait of the Engraver Francesco Bartolozzi,http://www.tate.org.uk/art/artworks/abbott-por...,0.0,676.0,756.0,1968,0,0,Presented by Mrs M. Bernard 1968,"Leicestershire, United Kingdom",1760,"London, United Kingdom",1803
4,Male,"Abrahams, Ivor",artist,Fibreglass and polystyrene,http://www.tate.org.uk/art/images/work/T/T03/T...,Lady in Niche,http://www.tate.org.uk/art/artworks/abrahams-l...,762.0,1575.0,2095.0,1982,1970,1973,Purchased 1982,"Wigan, United Kingdom",1935,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3326,Male,"Zuccarelli, Francesco",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T04/T...,A Landscape with the Story of Cadmus Killing t...,http://www.tate.org.uk/art/artworks/zuccarelli...,0.0,1572.0,1264.0,1985,1760,1765,Purchased 1985,Italia,1702,Firenze,1788
3327,Male,"Zuloaga, Ignacio",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/N/N01/N...,View of the Escorial,http://www.tate.org.uk/art/artworks/zuloaga-vi...,0.0,406.0,292.0,1923,1900,1905,Presented by T.W. Bacon through the Art Fund 1923,Espaa,1870,Espaa,1945
3328,Male,"Zyw, Aleksander",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T00/T...,Light,http://www.tate.org.uk/art/artworks/zyw-light-...,28.0,662.0,934.0,1962,1950,1957,Presented by Lady Alice Egerton through the Fr...,Polska,1905,NaN,1995
3329,Male,"di Suvero, Mark",artist,Lithograph on paper,NaN,Tetra,http://www.tate.org.uk/art/artworks/di-suvero-...,0.0,843.0,1152.0,2004,1970,1976,Presented by Tyler Graphics Ltd in honour of P...,"Shanghai, Zhonghua",1933,NaN,0
3330,Male,"van Elk, Ger",artist,"Photograph, colour, on paper with acrylic pain...",NaN,Lunch II,http://www.tate.org.uk/art/artworks/van-elk-lu...,0.0,1000.0,800.0,1980,1970,1976,Purchased 1980,"Amsterdam, Nederland",1941,NaN,0

In [46]:
data.drop_duplicates(subset = ['data.title'],keep='first')   #keeps 1st row and drops the last row with same data

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
0,Female,"Abakanowicz, Magdalena",artist,Burlap and resin,http://www.tate.org.uk/art/images/work/T/T12/T...,Backs,http://www.tate.org.uk/art/artworks/abakanowic...,0.0,0.0,0.0,2009,1970,1976,Presented anonymously 2009,Polska,1930,NaN,0
1,Male,"Abbey, Edwin Austin",artist,Ink on paper,http://www.tate.org.uk/art/images/work/N/N03/N...,Illustration to Judith Shakespeare,http://www.tate.org.uk/art/artworks/abbey-illu...,0.0,419.0,305.0,1924,1880,1883,Presented by a group of admirers through John ...,"Philadelphia, United States",1852,"London, United Kingdom",1911
2,Female,"Abbott, Berenice",artist,"Photograph, gelatin silver print on paper",NaN,Tri-Boro Barber Shop,http://www.tate.org.uk/art/artworks/abbott-tri...,0.0,200.0,250.0,2010,1930,1935,Accepted by HM Government in lieu of inheritan...,"Springfield, United States",1898,"Monson, United States",1991
3,Male,"Abbott, Lemuel Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T01/T...,Portrait of the Engraver Francesco Bartolozzi,http://www.tate.org.uk/art/artworks/abbott-por...,0.0,676.0,756.0,1968,0,0,Presented by Mrs M. Bernard 1968,"Leicestershire, United Kingdom",1760,"London, United Kingdom",1803
4,Male,"Abrahams, Ivor",artist,Fibreglass and polystyrene,http://www.tate.org.uk/art/images/work/T/T03/T...,Lady in Niche,http://www.tate.org.uk/art/artworks/abrahams-l...,762.0,1575.0,2095.0,1982,1970,1973,Purchased 1982,"Wigan, United Kingdom",1935,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3326,Male,"Zuccarelli, Francesco",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T04/T...,A Landscape with the Story of Cadmus Killing t...,http://www.tate.org.uk/art/artworks/zuccarelli...,0.0,1572.0,1264.0,1985,1760,1765,Purchased 1985,Italia,1702,Firenze,1788
3327,Male,"Zuloaga, Ignacio",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/N/N01/N...,View of the Escorial,http://www.tate.org.uk/art/artworks/zuloaga-vi...,0.0,406.0,292.0,1923,1900,1905,Presented by T.W. Bacon through the Art Fund 1923,Espaa,1870,Espaa,1945
3328,Male,"Zyw, Aleksander",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T00/T...,Light,http://www.tate.org.uk/art/artworks/zyw-light-...,28.0,662.0,934.0,1962,1950,1957,Presented by Lady Alice Egerton through the Fr...,Polska,1905,NaN,1995
3329,Male,"di Suvero, Mark",artist,Lithograph on paper,NaN,Tetra,http://www.tate.org.uk/art/artworks/di-suvero-...,0.0,843.0,1152.0,2004,1970,1976,Presented by Tyler Graphics Ltd in honour of P...,"Shanghai, Zhonghua",1933,NaN,0
3330,Male,"van Elk, Ger",artist,"Photograph, colour, on paper with acrylic pain...",NaN,Lunch II,http://www.tate.org.uk/art/artworks/van-elk-lu...,0.0,1000.0,800.0,1980,1970,1976,Purchased 1980,"Amsterdam, Nederland",1941,NaN,0

In [47]:
data.drop_duplicates(subset = ['data.title'],keep='last',inplace=True)   #keeps 1st row and drops the last row with same data

In [48]:
data.drop_duplicates(subset = ['data.title'],keep=False)   #Does not keep the none of the duplicated data

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
0,Female,"Abakanowicz, Magdalena",artist,Burlap and resin,http://www.tate.org.uk/art/images/work/T/T12/T...,Backs,http://www.tate.org.uk/art/artworks/abakanowic...,0.0,0.0,0.0,2009,1970,1976,Presented anonymously 2009,Polska,1930,NaN,0
1,Male,"Abbey, Edwin Austin",artist,Ink on paper,http://www.tate.org.uk/art/images/work/N/N03/N...,Illustration to Judith Shakespeare,http://www.tate.org.uk/art/artworks/abbey-illu...,0.0,419.0,305.0,1924,1880,1883,Presented by a group of admirers through John ...,"Philadelphia, United States",1852,"London, United Kingdom",1911
2,Female,"Abbott, Berenice",artist,"Photograph, gelatin silver print on paper",NaN,Tri-Boro Barber Shop,http://www.tate.org.uk/art/artworks/abbott-tri...,0.0,200.0,250.0,2010,1930,1935,Accepted by HM Government in lieu of inheritan...,"Springfield, United States",1898,"Monson, United States",1991
3,Male,"Abbott, Lemuel Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T01/T...,Portrait of the Engraver Francesco Bartolozzi,http://www.tate.org.uk/art/artworks/abbott-por...,0.0,676.0,756.0,1968,0,0,Presented by Mrs M. Bernard 1968,"Leicestershire, United Kingdom",1760,"London, United Kingdom",1803
4,Male,"Abrahams, Ivor",artist,Fibreglass and polystyrene,http://www.tate.org.uk/art/images/work/T/T03/T...,Lady in Niche,http://www.tate.org.uk/art/artworks/abrahams-l...,762.0,1575.0,2095.0,1982,1970,1973,Purchased 1982,"Wigan, United Kingdom",1935,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3327,Male,"Zuloaga, Ignacio",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/N/N01/N...,View of the Escorial,http://www.tate.org.uk/art/artworks/zuloaga-vi...,0.0,406.0,292.0,1923,1900,1905,Presented by T.W. Bacon through the Art Fund 1923,Espaa,1870,Espaa,1945
3328,Male,"Zyw, Aleksander",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T00/T...,Light,http://www.tate.org.uk/art/artworks/zyw-light-...,28.0,662.0,934.0,1962,1950,1957,Presented by Lady Alice Egerton through the Fr...,Polska,1905,NaN,1995
3329,Male,"di Suvero, Mark",artist,Lithograph on paper,NaN,Tetra,http://www.tate.org.uk/art/artworks/di-suvero-...,0.0,843.0,1152.0,2004,1970,1976,Presented by Tyler Graphics Ltd in honour of P...,"Shanghai, Zhonghua",1933,NaN,0
3330,Male,"van Elk, Ger",artist,"Photograph, colour, on paper with acrylic pain...",NaN,Lunch II,http://www.tate.org.uk/art/artworks/van-elk-lu...,0.0,1000.0,800.0,1980,1970,1976,Purchased 1980,"Amsterdam, Nederland",1941,NaN,0
3331,Male,"tyrsk, Jindrich",artist,"Photograph, black and white, on paper",http://www.tate.org.uk/art/images/work/P/P79/P...,Untitled,http://www.tate.org.uk/art/artworks/styrsky-un...,0.0,0.0,0.0,2007,1930,1934,Purchased 2007,NaN,1899,"Praha, Cesk Republika",1942

In [49]:
data = pd.read_csv('tate.csv',low_memory=False)

In [50]:
data.shape

(3332, 18)

In [51]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
3327    False
3328    False
3329    False
3330    False
3331    False
Length: 3332, dtype: bool

In [52]:
data.loc[data.duplicated()]   #not fully duplicated

Empty DataFrame
Columns: [artist.gender, artist.name, artist.role, data.medium, data.thumbnail, data.title, data.url, dimensions.depth, dimensions.height, dimensions.width, metadata.acquisition date, metadata.creation decade, metadata.creation year, metadata.credit, artist.birth.location, artist.birth.year, artist.death.location, artist.death.year]
Index: []

In [53]:
data.duplicated(subset = ['data.title'],keep=False)    #to find duplicates

0       False
1       False
2       False
3       False
4       False
        ...
3327    False
3328    False
3329    False
3330    False
3331     True
Length: 3332, dtype: bool

In [56]:
data.loc[data.duplicated(subset = ['data.title'],keep=False)]     #If'Not known'in the column->not fully duplicates

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
24,Male,"Ajmone, Giuseppe",artist,Oil paint on canvas,NaN,Autumn,http://www.tate.org.uk/art/artworks/ajmone-aut...,0.0,648.0,997.0,1960,1950,1959,Presented by Professor Gino Ghiringhelli 1960,"Carpignano Sesia, Italia",1923,NaN,2005
54,Male,"Als, Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T13/T...,Untitled,http://www.tate.org.uk/art/artworks/alys-untit...,20.0,208.0,159.0,2011,2000,2000,Presented by the artist 2010,"Antwerpen, Belgi",1959,NaN,0
66,Male,"Angellis, Peter",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T00/T...,Conversation Piece,http://www.tate.org.uk/art/artworks/angellis-c...,0.0,797.0,937.0,1965,1710,1715,Presented by the Friends of the Tate Gallery 1965,"Dunkerque, France",1685,"Rennes, France",1734
67,Male,"Annesley, David",artist,Painted steel,http://www.tate.org.uk/art/images/work/T/T01/T...,Untitled,http://www.tate.org.uk/art/artworks/annesley-u...,610.0,2470.0,2222.0,1970,1960,1968,Presented by Alistair McAlpine (later Lord McA...,"London, United Kingdom",1936,NaN,0
73,Male,"Anuszkiewicz, Richard",artist,Screenprint on paper,http://www.tate.org.uk/art/images/work/P/P01/P...,Untitled,http://www.tate.org.uk/art/artworks/anuszkiewi...,0.0,619.0,619.0,1976,1960,1965,"Presented by the Museum of Modern Art, New Yor...","Erie, United States",1930,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3285,Male,"Wyckaert, Maurice",artist,Lithograph on paper,http://www.tate.org.uk/art/images/work/P/P03/P...,[no title],http://www.tate.org.uk/art/artworks/wyckaert-n...,0.0,467.0,546.0,1978,1970,1975,Presented by the Asger Jorn Foundation 1978,"Bruxelles, Belgi",1923,"Bruxelles, Belgi",1996
3295,Male,"Yale, Brian",artist,Printed papers and graphite on map on board,NaN,[no title],http://www.tate.org.uk/art/artworks/yale-no-ti...,0.0,498.0,600.0,1976,1970,1971,"Presented by John Berry 1976, accessioned 1991","Staffordshire, United Kingdom",1936,NaN,2009
3297,Male,"Yamaguchi, Katsuhiro",artist,"Photograph, gelatin silver print on paper",NaN,Composition for APN,http://www.tate.org.uk/art/artworks/yamaguchi-...,0.0,114.0,153.0,2012,1950,1953,Purchased 2012,"Tokyo, Nihon",1928,NaN,0
3314,Male,"Zack, Leon",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T00/T...,Painting,http://www.tate.org.uk/art/artworks/zack-paint...,0.0,1305.0,975.0,1959,1950,1952,Purchased 1959,"Nizhniy Novgorod, Rossiya",1892,NaN,1980
3331,Male,"tyrsk, Jindrich",artist,"Photograph, black and white, on paper",http://www.tate.org.uk/art/images/work/P/P79/P...,Untitled,http://www.tate.org.uk/art/artworks/styrsky-un...,0.0,0.0,0.0,2007,1930,1934,Purchased 2007,NaN,1899,"Praha, Cesk Republika",1942

In [59]:
data.loc[data['data.medium'].str.contains('Oil paint on canvas')]   #found duplicates in 'medium'

,artist.gender,artist.name,artist.role,data.medium,data.thumbnail,data.title,data.url,dimensions.depth,dimensions.height,dimensions.width,metadata.acquisition date,metadata.creation decade,metadata.creation year,metadata.credit,artist.birth.location,artist.birth.year,artist.death.location,artist.death.year
3,Male,"Abbott, Lemuel Francis",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T01/T...,Portrait of the Engraver Francesco Bartolozzi,http://www.tate.org.uk/art/artworks/abbott-por...,0.0,676.0,756.0,1968,0,0,Presented by Mrs M. Bernard 1968,"Leicestershire, United Kingdom",1760,"London, United Kingdom",1803
11,Male,"Adams, Harry William",artist,Oil paint on canvas,NaN,Winters Sleep,http://www.tate.org.uk/art/artworks/adams-wint...,0.0,1841.0,1226.0,1900,1900,1900,Presented by the Trustees of the Chantrey Bequ...,"Worcester, United Kingdom",1868,"Worcester, United Kingdom",1947
12,Male,"Adams, Norman",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T05/T...,Christs Cross and Adams Tree,http://www.tate.org.uk/art/artworks/adams-chri...,0.0,1526.0,1270.0,1990,1980,1989,Presented by the Trustees of the Chantrey Bequ...,"London, United Kingdom",1927,NaN,2005
15,Male,"Adler, Jankel",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T00/T...,The Mutilated,http://www.tate.org.uk/art/artworks/adler-the-...,0.0,1118.0,864.0,1960,1940,1942,Presented by Robert Strauss 1960,"Tuszyn, Polska",1895,"Aldbourne, United Kingdom",1949
16,Female,"Adshead, Mary",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T07/T...,The Cruise,http://www.tate.org.uk/art/artworks/adshead-th...,0.0,1822.0,1420.0,1997,1930,1934,Purchased 1997,"London, United Kingdom",1904,"Hampstead, United Kingdom",1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3318,Male,"Zhang, Enli",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T13/T...,Bucket 8,http://www.tate.org.uk/art/artworks/zhang-buck...,0.0,994.0,995.0,2011,2000,2007,Purchased with funds provided by the Asia Paci...,"Jilin, Zhonghua",1965,NaN,0
3323,Male,"Zoffany, Johan",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T12/T...,Colonel Blair with his Family and an Indian Ayah,http://www.tate.org.uk/art/artworks/zoffany-co...,0.0,1346.0,965.0,2008,1780,1786,"Bequeathed by Simon Sainsbury 2006, accessione...","Frankfurt am Main, Deutschland",1733,"London, United Kingdom",1810
3326,Male,"Zuccarelli, Francesco",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T04/T...,A Landscape with the Story of Cadmus Killing t...,http://www.tate.org.uk/art/artworks/zuccarelli...,0.0,1572.0,1264.0,1985,1760,1765,Purchased 1985,Italia,1702,Firenze,1788
3327,Male,"Zuloaga, Ignacio",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/N/N01/N...,View of the Escorial,http://www.tate.org.uk/art/artworks/zuloaga-vi...,0.0,406.0,292.0,1923,1900,1905,Presented by T.W. Bacon through the Art Fund 1923,Espaa,1870,Espaa,1945
3328,Male,"Zyw, Aleksander",artist,Oil paint on canvas,http://www.tate.org.uk/art/images/work/T/T00/T...,Light,http://www.tate.org.uk/art/artworks/zyw-light-...,28.0,662.0,934.0,1962,1950,1957,Presented by Lady Alice Egerton through the Fr...,Polska,1905,NaN,1995